version: "3.7"

services:
  backend:
    container_name: backend
    restart: unless-stopped
    build: ./backend
    ports:
      - "5000:5000"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - mern
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    restart: unless-stopped
    build: ./frontend
    environment:
      - NODE_PATH=/app/src
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mern

  mongo:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: node-app
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - mern

networks:
  mern:

volumes:
  mongo_data: {}
  mongo_config: {}
